# Generated by Django 4.1.1 on 2022-10-13 11:21

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=True, max_length=255, null=True, upload_to=authentication.models.get_profile_image_filepath),
        ),
    ]
